version: '3'
services:
 nginx:
  image: nginx:latest
  ports:
   - "80:8000"
  volumes:
   - ./static:/static
   - ./nginx:/etc/nginx/conf.d
  depends_on:
   - web
 web:
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/surin_django_study

