version: '3'
services:
 nginx:
  image: nginx:latest
  ports:
   - "80:80"
  volumes:
   - ./static:/static
   - ./nginx:/etc/nginx/conf.d
   - ./nginx/nginx.conf:/etc/nginx/sites-avaliable/
   - ./nginx/nginx.conf:/etc/nginx/sites-enabled/
  depends_on:
   - web
 web:
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/surin_django_study

