version: '3'
services:
 nginx:
  image: nginx:latest
  ports:
   - "80:80"
  volumes:
   - ./static:/surin_django_study/static
   - ./nginx:etc/nginx/nginx.conf
  depends_on:
   - web
 web:
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/server

