# Generated by Django 4.0.3 on 2022-03-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nutrition',
            field=models.JSONField(default='{}'),
        ),
    ]
