# Generated by Django 4.0.3 on 2022-03-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_rename_category_brand_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cafe/review/images'),
        ),
    ]
