# Generated by Django 4.0.3 on 2022-03-08 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_alter_review_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='hot_size',
            new_name='hot_sizes',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ice_size',
            new_name='ice_sizes',
        ),
    ]
