# Generated by Django 4.0.3 on 2022-03-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0008_alter_brand_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
