# Generated by Django 4.0.3 on 2022-03-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_product_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='score',
            new_name='total_score',
        ),
    ]
