# Generated by Django 4.0.3 on 2022-03-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0011_alter_review_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_score',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
