# Generated by Django 4.0.3 on 2022-03-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0013_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hot_sizes',
            field=models.ManyToManyField(blank=True, related_name='hot_sizes', to='cafe.size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ice_sizes',
            field=models.ManyToManyField(blank=True, related_name='ice_sizes', to='cafe.size'),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_score',
            field=models.FloatField(blank=True, default=0, editable=False),
        ),
    ]
